import { Component, ElementRef, EventEmitter, Input, OnDestroy, OnInit, Output, ViewChild, inject, signal } from '@angular/core';
import { NgFor, NgIf } from '@angular/common';
import { firstValueFrom } from 'rxjs';
import * as THREE from 'three';
import { ModelLibraryApiService, ModelLibraryEntryDto } from '../../../api/model-library-api.service';
import { ModelImportService } from '../../../geometry/model-import.service';
import { disposeObject3D } from '../../../geometry/dispose-object3d';

type ThumbnailState = { kind: 'loading' } | { kind: 'ready'; dataUrl: string } | { kind: 'error' };

const THUMBNAIL_SIZE = 140;

// "Обрати сітку" opens this in place of the old plain <select> - a grid of
// cards, one per server model-library entry, each showing a rendered
// preview of the actual geometry plus its short characteristics (name,
// size, upload date) instead of just a filename in a dropdown row.
//
// Every card's preview is generated by downloading that entry's bytes and
// running them through the SAME ModelImportService.loadFromFile pipeline
// used for a real import (so the preview is the real geometry, not a
// placeholder icon), then rendering it once into ONE shared, offscreen
// WebGLRenderer this component owns for its own lifetime. Deliberately one
// renderer reused sequentially across every card rather than one WebGL
// context per card - the app already hit Chrome's ~16-context ceiling once
// this session (ZonePaintingComponent/SurfaceZonePaintingComponent/
// SixViewOverlayComponent all had to become lazy about their own contexts
// because of it), and a library grid can easily have more entries than that.
@Component({
  selector: 'app-model-library-picker',
  standalone: true,
  imports: [NgFor, NgIf],
  templateUrl: './model-library-picker.component.html',
  styleUrl: './model-library-picker.component.scss'
})
export class ModelLibraryPickerComponent implements OnInit, OnDestroy {
  @Input({ required: true }) entries: ModelLibraryEntryDto[] = [];
  @Output() readonly picked = new EventEmitter<ModelLibraryEntryDto>();
  @Output() readonly closed = new EventEmitter<void>();

  @ViewChild('thumbCanvas', { static: true }) private thumbCanvasRef!: ElementRef<HTMLCanvasElement>;

  private readonly modelLibraryApi = inject(ModelLibraryApiService);
  private readonly modelImport = inject(ModelImportService);

  private readonly thumbnails = signal<Record<string, ThumbnailState>>({});

  private renderer: THREE.WebGLRenderer | null = null;
  private camera: THREE.PerspectiveCamera | null = null;
  private scene: THREE.Scene | null = null;
  // Guards against a thumbnail landing after the dialog was already closed
  // (user clicks a card or the backdrop while a download/parse for a LATER
  // card in the queue is still in flight) - checked between every await in
  // renderThumbnailsSequentially so nothing touches a disposed renderer.
  private cancelled = false;

  ngOnInit(): void {
    const canvas = this.thumbCanvasRef.nativeElement;
    // preserveDrawingBuffer: true - toDataURL below needs to read back
    // whatever was last drawn; without it the browser is free to have
    // already cleared the buffer by the time toDataURL runs.
    this.renderer = new THREE.WebGLRenderer({ canvas, antialias: true, preserveDrawingBuffer: true });
    this.renderer.setSize(THUMBNAIL_SIZE, THUMBNAIL_SIZE, false);
    this.renderer.setClearColor(0x1e1f22, 1);

    this.scene = new THREE.Scene();
    this.scene.add(new THREE.AmbientLight(0xffffff, 0.6));
    const key = new THREE.DirectionalLight(0xffffff, 1.2);
    key.position.set(1, 1.5, 2);
    this.scene.add(key);

    this.camera = new THREE.PerspectiveCamera(40, 1, 0.01, 1000);

    void this.renderThumbnailsSequentially();
  }

  ngOnDestroy(): void {
    this.cancelled = true;
    // dispose() alone only frees three.js's own CPU-side bookkeeping - it
    // does NOT ask the browser to actually free the underlying WebGL
    // context (see the same fix in SixViewOverlayComponent/ZonePaintingComponent/
    // SurfaceZonePaintingComponent's own teardownRenderers). forceContextLoss()
    // is the actual, synchronous release this modal's context needs on close.
    this.renderer?.dispose();
    this.renderer?.forceContextLoss();
    this.renderer = null;
  }

  private async renderThumbnailsSequentially(): Promise<void> {
    for (const entry of this.entries) {
      if (this.cancelled) {
        return;
      }
      this.setStatus(entry.id, { kind: 'loading' });
      try {
        const bytes = await firstValueFrom(this.modelLibraryApi.download(entry.id));
        if (this.cancelled) {
          return;
        }
        const file = new File([bytes], entry.fileName);
        const object = await firstValueFrom(this.modelImport.loadFromFile(file));
        if (this.cancelled) {
          disposeObject3D(object);
          return;
        }
        const dataUrl = this.renderThumbnail(object);
        disposeObject3D(object);
        this.setStatus(entry.id, { kind: 'ready', dataUrl });
      } catch {
        this.setStatus(entry.id, { kind: 'error' });
      }
    }
  }

  private renderThumbnail(object: THREE.Object3D): string {
    const renderer = this.renderer!;
    const scene = this.scene!;
    const camera = this.camera!;

    scene.add(object);
    const sphere = new THREE.Box3().setFromObject(object).getBoundingSphere(new THREE.Sphere());
    const radius = Math.max(sphere.radius, 1e-3);
    const distance = (radius / Math.sin((camera.fov * Math.PI) / 360)) * 1.35;
    camera.position
      .copy(sphere.center)
      .add(new THREE.Vector3(1, 0.8, 1).normalize().multiplyScalar(distance));
    camera.near = distance / 100;
    camera.far = distance * 10;
    camera.lookAt(sphere.center);
    camera.updateProjectionMatrix();

    renderer.render(scene, camera);
    const dataUrl = renderer.domElement.toDataURL('image/png');
    scene.remove(object);
    return dataUrl;
  }

  private setStatus(id: string, state: ThumbnailState): void {
    this.thumbnails.update(map => ({ ...map, [id]: state }));
  }

  getThumbnail(id: string): ThumbnailState {
    return this.thumbnails()[id] ?? { kind: 'loading' };
  }

  formatSize(bytes: number): string {
    if (bytes < 1024) {
      return `${bytes} B`;
    }
    if (bytes < 1024 * 1024) {
      return `${(bytes / 1024).toFixed(1)} KB`;
    }
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  }

  formatDate(iso: string): string {
    return new Date(iso).toLocaleDateString('uk-UA', { day: '2-digit', month: '2-digit', year: 'numeric' });
  }

  onPick(entry: ModelLibraryEntryDto): void {
    this.picked.emit(entry);
  }

  onBackdropClick(): void {
    this.closed.emit();
  }
}
